apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::446807110235:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-IZAB7EFZX8JL
      username: system:node:{{EC2PrivateDNSName}}
      - system:masters
      rolearn: arn:aws:iam::446807110235:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-10-22T16:42:07Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "2644"
  uid: df48dff6-fd48-4d38-900f-177cfd9260c0
